<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Cuenta',
    'Address' => 'Dirección',
    'Before saving changes, it is highly recomended testing each protocol you are going to use' => 'Antes de guardar los cambios, es altamente recomendable probar cada protocolo que va a utilizar',
    'Draft folder' => 'Carpeta de borradores',
    'Folders' => 'Carpetas',
    'Host' => 'Host',
    'ID' => 'ID',
    'IMAP configuration' => 'Configuración IMAP',
    'IMAP port' => 'Puerto IMAP',
    'Imap Encryption' => 'Cifrado IMAP',
    'Imap Validate Cert' => 'Validar certificado IMAP',
    'Inbox folder' => 'Carpeta de entrada',
    'Incoming server' => 'Servidor de entrada',
    'None' => 'Ninguno',
    'Outgoing server' => 'Servidor de salida',
    'Password' => 'Contraseña',
    'SMTP configuration' => 'Configuración SMTP',
    'SMTP port' => 'Puerto SMTP',
    'Save' => 'Guardar',
    'Sent folder' => 'Carpeta de enviados',
    'Smtp Encryption' => 'Cifrado SMTP',
    'Smtp Validate Cert' => 'Validar certificado SMTP',
    'Test IMAP' => 'Probar IMAP',
    'Test SMTP' => 'Probar SMTP',
    'Trash folder' => 'Carpeta de papelera',
    'User' => 'Usuario',
];
