<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => 'Cuenta',
    'Address' => 'Dirección',
    'Are you sure you want to delete this item?' => '¿Está seguro de que desea eliminar este elemento?',
    'Before saving changes, it is highly recomended testing each protocol you are going to use' => 'Antes de guardar los cambios, es altamente recomendable probar cada protocolo que va a utilizar',
    'Configuration seems ok' => 'La configuración parece correcta',
    'Create Email Account' => 'Crear cuenta de correo',
    'Delete' => 'Eliminar',
    'Draft folder' => 'Carpeta de borradores',
    'Email Accounts' => 'Cuentas de correo',
    'Folders' => 'Carpetas',
    'Folders configuration has been set to automatically detected within the account, but changes has not been stored.' => 'La configuración de las carpetas se ha establecido para detectarlas automáticamente dentro de la cuenta, pero los cambios no se han guardado.',
    'ID' => 'ID',
    'IMAP configuration' => 'Configuración IMAP',
    'IMAP configuration seems ok' => 'La configuración IMAP parece correcta',
    'IMAP port' => 'Puerto IMAP',
    'Imap Encryption' => 'Cifrado IMAP',
    'Imap Validate Cert' => 'Validar certificado IMAP',
    'Important' => 'Importante',
    'Inbox folder' => 'Carpeta de entrada',
    'Incoming server' => 'Servidor de entrada',
    'None' => 'Ninguno',
    'Outgoing server' => 'Servidor de salida',
    'Password' => 'Contraseña',
    'Reset' => 'Reiniciar',
    'SMTP configuration' => 'Configuración SMTP',
    'SMTP port' => 'Puerto SMTP',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'Sent folder' => 'Carpeta de enviados',
    'Smtp Encryption' => 'Cifrado SMTP',
    'Smtp Validate Cert' => 'Validar certificado SMTP',
    'Test IMAP' => 'Probar IMAP',
    'Test SMTP' => 'Probar SMTP',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'Trash folder' => 'Carpeta de papelera',
    'Update' => 'Actualizar',
    'Update Email Account: {name}' => 'Actualizar cuenta de correo: {name}',
    'User' => 'Usuario',
    'Wrong configuration' => 'Configuración incorrecta',
    'Invalid email address' => 'Dirección de correo no válida',
    'Try automatic configuration' => 'Intentar configuración automática',
    'Unable to connect to the server.' => 'No se puede conectar al servidor.',
];
